In [1]:
import numpy as np
import scipy.linalg

In [2]:
a=[[1,2,3],[4,5,6],[7,8,9]]

In [4]:
np.ndim(a)

2

In [5]:
np.size(a)

9

In [7]:
n=2
np.shape(a[n-1])

(3,)

In [8]:
np.array([[1. ,2. ,3.], [4. ,5. ,6.]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [14]:
a=[8]
b=[10]
c=[11]
d=[13]
np.block([[a, b], [c, d]])

array([[[ 8],
        [10]],

       [[11],
        [13]]])

In [56]:
a[1,4]

8.0

In [15]:
a[-1]

8

In [41]:
a
a[1]

(29209, 8, 8, 8, 8, 8)

In [50]:
a=np.array([[1. ,2. ,3.,4.,5.,6.], [4. ,5. ,6.,7.,8.,9.]])
a[1,4]

8.0

In [51]:
a[1]

array([4., 5., 6., 7., 8., 9.])

In [52]:
a[0:5]

array([[1., 2., 3., 4., 5., 6.],
       [4., 5., 6., 7., 8., 9.]])

In [54]:
a[-5:]

array([[1., 2., 3., 4., 5., 6.],
       [4., 5., 6., 7., 8., 9.]])

In [55]:
a[0:3, 4:9]

array([[5., 6.],
       [8., 9.]])

In [59]:
a=np.array([[1. ,2. ,3.,4.,5.,6.], [4. ,5. ,6.,7.,8.,9.], [4. ,5. ,6.,7.,8.,9.], [4. ,5. ,6.,7.,8.,9.], [4. ,5. ,6.,7.,8.,9.]])
a[np.ix_([1, 3, 4], [0, 2])]

array([[4., 6.],
       [4., 6.],
       [4., 6.]])

In [60]:
a[2:21:2,:]

array([[4., 5., 6., 7., 8., 9.],
       [4., 5., 6., 7., 8., 9.]])

In [61]:
a[ ::2,:]

array([[1., 2., 3., 4., 5., 6.],
       [4., 5., 6., 7., 8., 9.],
       [4., 5., 6., 7., 8., 9.]])

In [70]:
a=np.array([[1. ,2. ], [4. ,5.]])
a[::-1,:]

array([[4., 5.],
       [1., 2.]])

In [71]:
a[np.r_[:len(a),0]]

array([[1., 2.],
       [4., 5.],
       [1., 2.]])

In [72]:
a.transpose()

array([[1., 4.],
       [2., 5.]])

In [73]:
a.conj().transpose()

array([[1., 4.],
       [2., 5.]])

In [75]:
b=np.array([[1. ,2. ], [4. ,5.]])
a@b

array([[ 9., 12.],
       [24., 33.]])

In [76]:
a*b

array([[ 1.,  4.],
       [16., 25.]])

In [80]:
a/6



array([[0.16666667, 0.33333333],
       [0.66666667, 0.83333333]])

In [78]:
a**3

array([[  1.,   8.],
       [ 64., 125.]])

In [79]:
(a>0.5)

array([[ True,  True],
       [ True,  True]])

In [81]:
np.nonzero(a > 0.5)

(array([0, 0, 1, 1]), array([0, 1, 0, 1]))

In [102]:
v=np.array([0,0])
a[:, v.T > 0.5]

array([], shape=(2, 0), dtype=float64)

In [105]:
a[a < 0.5]=0

In [106]:
a * (a > 0.5)

array([[1., 2.],
       [4., 5.]])

In [108]:
a[:] = 3

In [114]:
x=np.array([[1. ,2. ], [4. ,5.]])
y = x.copy()

In [115]:
y = x[1, :].copy()

In [116]:
y = x.flatten()

In [117]:
np.arange(1., 11.)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [118]:
np.arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [119]:
np.arange(1.,11.)[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [120]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [121]:
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [122]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [123]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [124]:
np.diag(a)

array([3., 3.])

In [125]:
np.diag(v, 0)

array([[0, 0],
       [0, 0]])

In [132]:
np.random.rand(3, 4)

array([[0.13598501, 0.53480611, 0.04603703, 0.29886836],
       [0.70527448, 0.52652296, 0.77579401, 0.3169213 ],
       [0.02532509, 0.51014615, 0.71533548, 0.71191955]])

In [133]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [134]:
np.mgrid[0:9.,0:6.]

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [141]:
np.ogrid[0:9.,0:6.]

[array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]),
 array([[0., 1., 2., 3., 4., 5.]])]

In [142]:
np.meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]),
 array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [144]:
np.ix_([1,2,4],[2,4,5])

(array([[1],
        [2],
        [4]]),
 array([[2, 4, 5]]))

In [146]:
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [157]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a,b.T),1)

array([[1, 2, 5],
       [3, 4, 6]])

In [158]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [159]:
a.max() 

4

In [160]:
a.max(0)

array([3, 4])

In [161]:
a.max(1)

array([2, 4])

In [162]:
np.maximum(a, b)

array([[5, 6],
       [5, 6]])

In [163]:
np.sqrt(v @ v)

0.0

In [165]:
np.logical_and(a,b)

array([[ True,  True],
       [ True,  True]])

In [166]:
np.logical_or(a,b)

array([[ True,  True],
       [ True,  True]])

In [167]:
a & b

array([[1, 2],
       [1, 4]])

In [168]:
a | b

array([[5, 6],
       [7, 6]])

In [170]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [171]:
np.linalg.pinv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [172]:
np.linalg.matrix_rank(a)

2

In [175]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
np.linalg.solve(a, b)

array([-1.,  1.])

In [177]:
np.linalg.solve(a.T, b.T)

array([1., 0.])

In [184]:
u, s, Vh = np.linalg.svd(a)
V=Vh.T
u.shape, s.shape, vh.shape

((2, 2), (2,), (2, 2))

In [209]:
a = np.array([[1,-2j],[2j,5]])
c = np.linalg.cholesky(a)
c

array([[1.+0.j, 0.+0.j],
       [0.+2.j, 1.+0.j]])

In [217]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
D,V = np.linalg.eig(a)
D
V

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

In [219]:
D,V = scipy.linalg.eig(a, b)
D
V

array([[-1.        , -0.40824829,  0.42174117],
       [-0.        ,  0.81649658, -0.30177341],
       [-0.        , -0.40824829, -0.85502467]])

In [226]:
from scipy.sparse.linalg import eigs
D,V = eigs(a, k = 3)
D
V

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

In [231]:
Q,R = scipy.linalg.qr(a)
R

array([[-8.12403840e+00, -9.60113630e+00, -1.10782342e+01],
       [ 0.00000000e+00,  9.04534034e-01,  1.80906807e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.77635684e-15]])

In [234]:
P,L,U = scipy.linalg.lu(a) 
U

array([[7.00000000e+00, 8.00000000e+00, 9.00000000e+00],
       [0.00000000e+00, 8.57142857e-01, 1.71428571e+00],
       [0.00000000e+00, 0.00000000e+00, 1.11022302e-16]])

In [241]:
scipy.sparse.linalg.cg

<function scipy.sparse.linalg.isolve.iterative.cg(A, b, x0=None, tol=1e-05, maxiter=None, M=None, callback=None, atol=None)>

In [244]:
a=np.array([1])
np.fft.fft(a)

array([1.+0.j])

In [246]:
np.fft.ifft(a)

array([1.+0.j])

In [247]:
np.sort(a) 

array([1])

In [256]:
a=np.array([[1,3,8],[8,3,4],[9,78,0]])
np.sort(a, axis = 1)

array([[ 1,  3,  8],
       [ 3,  4,  8],
       [ 0,  9, 78]])

In [258]:
I = np.argsort(a[:, 0]); b = a[I,:]
I

array([0, 1, 2])

In [263]:
x=np.array([[1,3,8],[8,3,4],[9,78,0]])
y=np.array([[1,3,8],[8,3,4],[9,78,0]])
x = scipy.linalg.lstsq(x, y)
x

(array([[ 1.00000000e+00,  1.41113177e-15, -1.72601811e-16],
        [ 1.40430112e-17,  1.00000000e+00,  2.77555756e-17],
        [-2.55933879e-16,  1.59594560e-16,  1.00000000e+00]]),
 array([], dtype=float64),
 3,
 array([78.67781502, 10.29178419,  5.64629104]))

In [268]:
from scipy import signal
x = np.linspace(0, 10, 20, endpoint=False)
y = np.cos(-x**2/6.0)
f = signal.resample(y, 100)
f

array([ 1.        ,  1.23283311,  1.31727019,  1.27302765,  1.14740269,
        0.99913207,  0.88078847,  0.82497964,  0.83806509,  0.90249922,
        0.98614323,  1.05486   ,  1.08402435,  1.06536954,  1.00747904,
        0.93050762,  0.85758366,  0.80620995,  0.78263328,  0.78081837,
        0.78588726,  0.78033048,  0.75048699,  0.69094819,  0.60552319,
        0.50478221,  0.40143727,  0.30548407,  0.22092394,  0.14511765,
        0.0707372 , -0.01068719, -0.10512733, -0.21370903, -0.33240564,
       -0.45366208, -0.56910426, -0.67215691, -0.75955883, -0.83131707,
       -0.88932657, -0.93540864, -0.9696874 , -0.98998822, -0.9924354 ,
       -0.97288395, -0.92847886, -0.85863231, -0.76502853, -0.65074937,
       -0.51903563, -0.37236513, -0.21236454, -0.04065068,  0.13978552,
        0.3233596 ,  0.50154373,  0.66375109,  0.79927642,  0.89960584,
        0.96017029,  0.98077748,  0.96447814,  0.91530208,  0.8358487 ,
        0.7258814 ,  0.58274561,  0.40370101,  0.18940426, -0.05

In [269]:
np.unique(a)

array([ 0,  1,  3,  4,  8,  9, 78])

In [270]:
a.squeeze()

array([[ 1,  3,  8],
       [ 8,  3,  4],
       [ 9, 78,  0]])